### ISSUE TITLE
program dependencies are not checked, facedetect: command not found

### ISSUE THREAD

**Issue by artlog** [foopgp/bash-libs#1]
If facedetect is not installed ( or was removed ) program starts then loop :

<13>May 10 16:35:35 pgpid-gen[44009]: Notice: Taking picture, please don't move (2 seconds) !
<13>May 10 16:35:38 pgpid-gen[44009]: Notice: ./pgpid-gen: line 417: facedetect: command not found

a general dependency & health check could be done to not loop and exit with request to install facedetect.

**Comment by artlog** [comment]
same issue for gm (graphicsmagick)

<13>May 10 16:39:58 pgpid-gen[44946]: Notice: ./pgpid-gen: ligne 443: gm : commande introuvable

**Comment by artlog** [comment]
wrong project ... this is for pgpid.

**Comment by jbar** [comment]
Moreover it is a packaging issue, not a pure software one.
